CREATE TABLE IF NOT EXISTS booklist (
    id VARCHAR(255)  PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    image VARCHAR(255) NOT NULL
);
--CREATE TABLE IF NOT EXISTS booklist (
--    id INT AUTO_INCREMENT PRIMARY KEY,
--    name VARCHAR(255) NOT NULL,
--    image VARCHAR(255) NOT NULL
--);

CREATE TABLE comments (
    BOOK_ID VARCHAR(255)  PRIMARY KEY,
    COMMENTER_NAME VARCHAR(255) NOT NULL,
    COMMENT_CONTENT TEXT,
    FOREIGN KEY (BOOK_ID) REFERENCES booklist(ID)
);

